### ISSUE TITLE
Morning Code Review Session

### ISSUE THREAD

**Issue by Calvinoea** [mariosknl/Positioning_Floating#3]
Great job! 👍  A lot of attention to detail in the code. 

The use of alt text is great. You may also consider whether more than one word could affect the search engine optimisation for the page . Some may suggest 10 - 15 words (maximum 120 characters) for alt text : https://www.sotechdesign.com.au/seo-how-many-words-long-to-make-image-alt-text/

**Comment by Theophile-Kango** [comment]
Thank you for your feedback. We will review our code
